version: "3"

includes:
  cluster:
    taskfile: operations/taskfiles/cluster.yml

  checks:
    taskfile: operations/taskfiles/checks.yml

  security:
    taskfile: operations/taskfiles/security.yml

  tofu:
    flatten: true
    taskfile: operations/taskfiles/opentofu.yml

  update:
    taskfile: operations/taskfiles/update.yml
