name: checks

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v23

      - name: Cache Nix
        uses: DeterminateSystems/magic-nix-cache-action@v14

      - name: Run checks
        run: nix develop .#ci --command task checks:all
